export const STRINGS = {
  COMPASS: "Compass",
  EXPLORE: "Explore",
  ACADEMEY: "Academy",
  NFTS: "NFTs",
  FOR_PROJECTS: "For Projects",
  NEW: "New",
  SIGN_IN: "Sign In",
  SEARCH_PLACEHOLDER: "Search for ecosystems, trending queues, etc.",
  ACADEMY_BOLD_1: "Intract users ",
  ACADEMY_BOLD_2: "$100 million ",
  ACADEMY_BOLD_3: "learn how to earn crypto!",
  ACADEMY_TEXT_1: "have together made more than ",
  ACADEMY_TEXT_2: "in web3.",
  ACADEMY_TEXT_3: "Join them and ",
};
